name: Publish Docs To GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
    
      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          output_dir: ./docs
          recurse: true
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
